export const GETPRODUCTDETAILS_START = "PRODUCTDETAILS_START";
export const GETPRODUCTDETAILS_SUCCESS = "PRODUCTDETAILS_SUCCESS";
export const GETPRODUCTDETAILS_FAILURE = "PRODUCTDETAILS_FAILURE";

export const GETSIMILARPROD_START = "SIMILARDETAILS_START";
export const GETSIMILARPROD_SUCCESS = "SIMILARDETAILS_SUCCESS";
export const GETSIMILARPROD_FAILURE = "SIMILARTAILS_FAILURE";

export const GETSEARCHDETAILS_START = "SEARCHDETAILS_START";
export const GETSEARCHDETAILS_SUCCESS = "SEARCHDETAILS_SUCCESS";
export const GETSEARCHDETAILS_FAILURE = "SEARCHDETAILS_FAILURE";

export const GETHOMEDETAILS_START = "HOMEDETAILS_START";
export const GETHOMEDETAILS_SUCCESS = "HOMEDETAILS_SUCCESS";
export const GETHOMEDETAILS_FAILURE = "HOMEDETAILS_FAILURE";
export const GETCOUNTRY_DETIALS="COUNTRY_DETAILS";
export const GETSTATE_DETAILS="STATE_DETAILS";
export const GETCITY_DETAILS="CITY_DETAILS"

export const ADD_ITEM="ADD_ITEM";
export const REMOVE_ITEM="REMOVE_ITEM";
export const ALL_PRODUCTS="ALL_PRODUCTS";

export const AUTH_SIGNUP="SIGNUP";
export const AUTH_LOGOUT="LOGOUT";
export const AUTH_SIGNIN="SIGNIN";
export const AUTH_OTP="OTP";

export const UPDATE_PROFILE_START="UPDATE_START";
export const UPDATE_PROFILE_SUCCESS="UPDATE_SUCCESS";
export const UPDATE_PROFILE_FAIL="UPDATE_FAIL";

export const ADD_FAVOURITE="ADD_FAVOURITE";
export const REMOVE_FAVOURITE="REMOVE_FAVOURITE";
export const GET_FAVOURITE="GET_FAVOURITE";

export const GET_NOTIFICATIONS="GET_NOTIFICATIONS"
export const REMOVE_NOTIFICATIONS="REMOVE_NOTIFICATIONS"